' ※ 本図は架空の組織図です
' ※ 拠点は package として表現しています

@startuml organization

object 会長 #ffffff {
  #高橋CEO
}
object 社長 #ffffff {
  #佐藤COO
}

package 本社 {
  object 総務部 {
    #田中（部長、本社統括）
    +中村
    +近藤（工場常駐）
  }
  object 管理部 {
    #山本（部長）
    +中村（総務部兼務)
  }
  object 営業部 {
    #加藤（部長）
    +鈴木（担当部長）
  }
  object 第1営業課  {
    #加藤（課長、営業部長兼務）
    +山田
    +小林
  }
  object 第2営業課  {
    #佐々木（課長）
    +山口
  }
}

package 工場 {
  object 生産管理部 {
    #井上（部長、工場統括）
    +木村
  }
  object 開発部 {
    #林（部長）
    +斉藤（主幹）
    +清水
    +山﨑
    +阿部
  }
  object 品質保証部 {
    #森（部長）
    +池田
  }
  object 製造部 {
    #橋本（部長）
  }
  object 製造1課 {
    #山下（課長）
    +石川（係長）
    +中島
    +伊藤
    +松本
  }
  object 製造2課 {
    #岡田（課長）
    +長谷川
    +佐藤 大
}

会長 -- 社長
社長 -- 総務部
社長 -- 管理部
社長 -- 営業部
社長 -- 生産管理部
社長 -- 開発部
社長 -- 品質保証部
社長 -- 製造部
営業部 -- 第1営業課
営業部 -- 第2営業課
製造部 -- 製造1課
製造部 -- 製造2課

総務部 -[hidden]r- 管理部
営業部 -[hidden]r- 生産管理部
開発部 -[hidden]r- 品質保証部

@enduml
