.TH DISKUTILITY-TIPS 7 "2026年3月" "個人メモ" "ユーザーガイド"
.SH 【名前】
diskutility-tips \- よく使うディスク操作関連ツールの例集
.SH 【使用例】
.TP
接続されているメディアを表示する：
.EX
% sudo camcontrol devlist
.EE
.TP
パーティション構成を表示する：
.EX
% sudo gpart show ada0
% sudo gpart show nda0
% sudo gpart show da0
.EE
.TP
ディスク詳細情報を表示する：
.EX
% sudo camcontrol identify ada0
% sudo camcontrol identify nda0
% sudo camcontrol inquiry da0
.EE
